// Nomes oficiais dos slash commands padronizados em inglês com o prefixo py-*
module.exports = {
  PING: 'py-ping',
  STATUS: 'py-status',
  HELP: 'py-help',
  WELCOME: 'py-welcome',
  SIXSEVEN: 'py-sixseven',
  SHIP: 'py-ship',
  DAILY: 'py-daily',
  WALLET: 'py-wallet',
  PROFILE: 'py-profile',
  MARRIAGE: 'py-marriage',
  DIVORCE: 'py-divorce',
  RANKING: 'py-rank',
  ECONOMY_CONFIG: 'py-ecoconfig',
  SET_ECONOMY: 'py-seteco',
  RESET_ECONOMY: 'py-reseteco',
  PROFESSION: 'py-profession',
  WORK: 'py-work',
  PET_EXPLORE: 'py-explore',
  PYMONS: 'py-pymons',
  PIXELMONSTERS: 'py-pymons',
  PET: 'py-pymons',
  PET_DUEL: 'py-duel',
  SHOP: 'py-shop',
  BUY: 'py-buy',
  SELL: 'py-sell',
  INVENTORY: 'py-inventory',
  USE: 'py-use',
  AGENDA: 'py-schedule',
  EMOJIS: 'py-emojis',
  DEX: 'py-dex',
  INVITE: 'py-invite',
  TRADE: 'py-trade',
  EXPEDITION: 'py-expedition',
  BOSS: 'py-boss',
  TAROT: 'py-tarot',
  VOTE: 'py-vote',
  LANGUAGE: 'py-language',
  BONUS: 'py-bonus',
};

