// Nomes oficiais dos slash commands padronizados em inglês com o prefixo py-*
module.exports = {
  PING: 'py-ping',
  STATUS: 'py-status',
  HELP: 'py-help',
  WELCOME: 'py-welcome',
  SIXSEVEN: 'py-sixseven',
  SHIP: 'py-ship',
  DAILY: 'py-daily',
  WALLET: 'py-wallet',
  PROFILE: 'py-profile',
  MARRIAGE: 'py-marriage',
  DIVORCE: 'py-divorce',
  RANKING: 'py-rank',
  ECONOMY_CONFIG: 'py-ecoconfig',
  SET_ECONOMY: 'py-seteco',
  RESET_ECONOMY: 'py-reseteco',
  PROFESSION: 'py-profession',
  WORK: 'py-work',
  SETUP: 'py-setup',
  AGENDA: 'py-schedule',
  EMOJIS: 'py-emojis',
  INVITE: 'py-invite',
  TAROT: 'py-tarot',
  VOTE: 'py-vote',
  LANGUAGE: 'py-language',
  BONUS: 'py-bonus',
  JOKENPO: 'py-jokenpo',
  COOKIE: 'py-cookie',
  LIKELY: 'py-likely',
  DICE: 'py-dice',
  COINFLIP: 'py-coinflip',
  ADMIN: 'py-admin',
  WIKI: 'py-wiki',
  EXPORT_MESSAGES: 'py-exportar',
  QUIZ: 'py-quiz',
  TERMS: 'py-terms',
  CHILD: 'py-child',
  MATH: 'py-math',
  TICTACTOE: 'py-tictactoe',
  MINESWEEPER: 'py-minesweeper',
};


